### ISSUE TITLE
add tests for repr

### ISSUE THREAD

**Issue by AlJohri** [pcattori/icicle#10]

**Comment by pcattori** [comment]
I think testing `repr` might be overkill. If you have a `FrozenDict`, its much easier to use its API rather than rely on parsing `repr`, so its not *really* part of the API, just there to make debugging easier. But maybe I'm wrong; Do you expect people to depend on the stability of `repr` in their code?

**Comment by AlJohri** [comment]
Haha it just looked intimidated on first read but you're probably right.

**Comment by AlJohri** [comment]
I was also not sure if there's anyway to get a cyclic reference in an immutable data structure like this - perhaps if you're converting a dict that already has one into a frozen dict?
